global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'clients'
    static_configs:
      - targets: ['clients:8000']

  - job_name: 'commande'
    static_configs:
      - targets: ['commande:8000']

  - job_name: 'panier'
    static_configs:
      - targets: ['panier:8000']

  - job_name: 'fastapi-interface'
    static_configs:
      - targets: ['interface1:8000', 'interface2:8000']
