name: Python application & Docker publish - Lab5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: lab2user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: lab2db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 src test

      - name: Initialize database (create tables)
        env:
          DATABASE_URL: postgresql+psycopg://lab2user:password@localhost/lab2db
        run: |
          source venv/bin/activate
          PYTHONPATH=src python -c "from common.database import init_db; init_db()"

      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg://lab2user:password@localhost/lab2db
        run: |
          source venv/bin/activate
          PYTHONPATH=src python -m pytest

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for all services
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-clients:latest
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-panier:latest
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-commande:latest
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-logistique:latest
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-magasin:latest
            ${{ secrets.DOCKER_USERNAME }}/log430-lab5-gateway:latest
